### ISSUE TITLE
websocket missing backend selection

### ISSUE THREAD

**Issue by mkmer** [abmantis/whirlpool-sixth-sense#11]
After some testing, no event based messages were appearing in the cli.py test (as well as HomeAssistant).  Looks like eventsocket.py didn't get the additions for backend selection and only connects to: websocketservice.wcloud-emea.eu-gb.containers.appdomain.cloud
There probably is a US version?

**Comment by abmantis** [comment]
Besides the websocket, is the rest working? At least here in Europe, they've changed their API and nothing works now :disappointed:

**Comment by mkmer** [comment]
I only have a washer/dryer - those are working fine, but have to set the integration to polling. Been running it in my instance of HA for a couple of weeks now.
I don't have any of the other appliances to test :(
If you would like to check out what I have, it's here (under the whirlpool branch):

https://github.com/mkmer/core.git

It's real close to being ready for a PR.

**Comment by mkmer** [comment]
@abmantis: Maybe I can just use the US version, but not sure if the polling features work for the other appliances. 
As of yesterday, I'm not getting a NS lookup error for the ebsocketservice.wcloud-emea.eu-gb.containers.appdomain.cloud address - looks like they moved the end point?!?!?

If they are changing the API in EU, US is probably not far behind :(

**Comment by abmantis** [comment]
@mkmer I just found the new ws url for EMEA: https://github.com/abmantis/whirlpool-sixth-sense/commit/8d8821bf483c0bcd8718e924566b61eb70e4ec22

Were you able to find the one for the US?

The API is back up. Not sure if they had to revert it or it was just temporarily down, but the app is still using the same old API.

**Comment by abmantis** [comment]
Apparently we can just fetch the WS URL, so it should now work for US too: https://github.com/abmantis/whirlpool-sixth-sense/commit/87ae0943ad4a3c18b40e17394ebba7dbd524933d
