### ISSUE TITLE
SSL Cert Verification fails

### ISSUE THREAD

**Issue by mkmer** [abmantis/whirlpool-sixth-sense#12]
Running the client in the US - all aiohttp calls fail the cert verification.

I have temporarily added verify_ssl = False to all .get and .post just to verify other functions are working - so far events are now connected an working.  Not exactly sure how else to get around this issue.

**Comment by abmantis** [comment]
Can you try changing `https://prod-api.whrcloud.com` to `https://api.whrcloud.com` on `whirlpool/backendselector.py`? That seems ok.

**Comment by mkmer** [comment]
That works.  
I was on the way to a proposed update in HomeAssistant a few months back - Once we get this working, I'll probably finish adding the washer/dryers and US/EU options to the HA integration (unless you're already working on it)

**Comment by abmantis** [comment]
Thanks. 
Regarding region selection, I was about to add that, I'm just missing the unit tests. Do you have it done already? If not, I can finish them up.
Regarding washer/dryers, since I don't have any please go ahead. You can use the branch from my PR as base since it supports the latest version of this lib.

**Comment by mkmer** [comment]
This is where I left off: (it's way behind the dev branch)
https://github.com/mkmer/core/tree/Whirlpool

After my work on AladdinConnect I know there is a bunch of work that needs to be done - advancing the naming conventions,  and not using "extra attributes".  There is one value that is needed from the washer related to time left - Cavity_TimeStatusEstTimeRemaining.  It would be great if you could add a property to read this value in washerdryer.py (otherwise I will need to get_all_attributes in HA side to grab it).

**Comment by abmantis** [comment]
Closing this since the SSL error is fixed with https://github.com/abmantis/whirlpool-sixth-sense/releases/tag/0.17.1
