### ISSUE TITLE
Eventsocket dies with no log as to why

### ISSUE THREAD

**Issue by mkmer** [abmantis/whirlpool-sixth-sense#17]
Current eventsocket code does not restart after 3 connection attempts and does not log the condition - results in a dead eventsocket task.  

For a long lived eventsocket, it should continue to retry forever.  At a minimum it should reset the retry count after a successful connection, and log when it stops trying.

https://github.com/abmantis/whirlpool-sixth-sense/pull/13 has retry counter removed.

**Comment by abmantis** [comment]
Fixed by #13
