### ISSUE TITLE
Adding integration

### ISSUE THREAD

**Issue by pedrofrpg** [abmantis/whirlpool-sixth-sense#31]
First of all congrats for this project @abmantis. I need your help please. The official whirlpool 6 sense integration doesn't work properly, how do I install this library in Homeassistant?

**Comment by abmantis** [comment]
Hi @pedrofrpg . Please post on the HA forum, since github tickets are not for user support. 
Nevertheless, you cannot just install the one from here without changes to the integration since it had some API breaking changes.
