### ISSUE TITLE
Updated Deployment Instructions

### ISSUE THREAD

**Issue by pavandave** [abmantis/whirlpool-sixth-sense#38]
I am trying to deploy this with HA and have looked through the initial supported Whirlpool Appliances but am unable to. How do I deploy this? I can't pull this through HACS so I think I'm missing something to connect the dots.

Can the readme be updated with better documentation or can someone help me and I can pull to update the readme after I have it deployed.

**Comment by abmantis** [comment]
This library is part of the Whirlpool integration that is already stock on HA.

**Comment by abmantis** [comment]
Ovens are not supported by the integration yet

**Comment by thepuncake** [comment]
> Ovens are not supported by the integration yet

So how can one use oven.py as seen in the list of files?

**Comment by abmantis** [comment]
> > Ovens are not supported by the integration yet
> 
> So how can one use oven.py as seen in the list of files?

Someone needs to integrate it on HA side.
