### ISSUE TITLE
Python required version minimum

### ISSUE THREAD

**Issue by NodeJSmith** [abmantis/whirlpool-sixth-sense#57]
Since the main use of this library is for HA and that runs Python 3.12 as of this week, are we able to reduce the Python required version minimum? If we move up to 3.10 or 3.11 we can take advantage of some of the newer features, and I don't know if there would be any downside to it.

@abmantis Thoughts? I'm not sure if there are more users or use cases that I'm not aware of for this library

**Comment by abmantis** [comment]
Yep, we can move up! If HA is now on 3.12, we can bump to 3.12.
