### ISSUE TITLE
EU/US vs brands

### ISSUE THREAD

**Issue by eskibars** [abmantis/whirlpool-sixth-sense#7]
Hey there!

As I started writing an integration for the oven (#6), I noticed that -- at least for me, it appears that logins are dependent on region, not on brand. Here in the US, we get both Maytag and Whirlpool brand appliances (my oven is Whirlpool) but it appears auth is not brand (only?) dependent, but region dependent.  Trying auth to `https://api.whrcloud.eu` gives a 400 error even with otherwise correct credentials for a Whirlpool-brand (oven) appliance for a US based account.  Using the Maytag brand (`-b maytag`) does auth the US based account, but the brand/url base are then wrong.  I don't have any other devices to test whether the brand matters or just the region, but the region definitely does.

I think we at least need to introduce a region parameter.  WDYT?

**Comment by abmantis** [comment]
Hey!

Yeah, I agree with adding the `region` parameter too! 
Thank you!

**Comment by mkmer** [comment]
Are either of you looking at updating the pipy version for this change? 

I too was looking at modifying or rewriting a custom HA integration floating around for the washer/dryer and would love to use this for the integration.  It should make getting it out of "custom" and into the core much easier.  

Alternately, maybe making one HA integration that discovers all SAIDs and adds everything it finds of the correct type?!?  
@abmantis it looks like you currently own the HA integration utilizing the DOMAIN of whirlpool.  Is that still true?

**Comment by abmantis** [comment]
@mkmer I don't "own" it. Anyone can submit changes to it. It just means that I was the one doing it and will be automatically notified to review PRs changing it.
My whirlpool appliance is currently off, so I haven't been doing much regarding this integration. Can you open a PR for HA with this?

**Comment by mkmer** [comment]
I certainly can open a PR, I really didn't want to start working on
something someone else was already doing.
For starters, I think the current version to pypi needs to be released (the
one with local (US/EU), and appliances in it).  As far as I can tell,
0.15.1 doesn't have it.  I'm not familiar with releases to pipy.

As soon as I get the alladin_connect PR finished and the latest is released
to pipy, I'll start working on a whirlpool integration that "hopefully"
finds everything - starting with what you have done and what the maytag
laundry guy has done.

I suppose I should also hunt for @eskibars work as well, looks like he has
an oven figured out.

**Comment by abmantis** [comment]
@mkmer I'll try to release it to pypi in the next couple days. You can point HA to this github repo to start working on it if you want to, without having to wait for it to be on pypi.

**Comment by abmantis** [comment]
@mkmer 0.16 release to pypi.
